# MUF/docker-compose.yml

include:
  - path: redis/docker-compose.yml
  - path: monitor/docker-compose.yml
  - path: terminal/docker-compose.yml

# ルート側でもネットワークの定義を共通化して参照します
networks:
  muf-network:
    external: true