# MUF/monitor/docker-compose.yml
services:
  muf-monitor:
    build: .
    container_name: muf-monitor
    environment:
      - REDIS_USERNAME=monitor
      - REDIS_PASSWORD=MonitorPass123
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-..}/muf:/app/muf:cached
      - ${LOCAL_WORKSPACE_FOLDER:-.}/monitor:/app/monitor:cached
      - ${LOCAL_WORKSPACE_FOLDER:-.}/monitor/logs:/app/monitor/logs:cached
    command: python monitor/main.py
    networks:
      - muf-network
    restart: always

networks:
  muf-network:
    name: muf-network
