services:
  muf-monitor:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    container_name: muf-monitor
    environment:
      - REDIS_HOST=muf-redis
      - TARGET_PATH=muf/*
#      - TARGET_PATH=muf/test/unit
    networks:
      - muf-network
    restart: unless-stopped

networks:
  muf-network:
    external: true