# terminal/docker-compose.yml
services:
  muf-terminal:
    build: .
    container_name: muf-terminal
    volumes:
      - ../muf:/app/muf
      - .:/app/terminal
    networks:
      - muf-network
    restart: always
    stdin_open: true
    tty: true
    command: python terminal/main.py

networks:
  muf-network:
    external: true