# terminal/docker-compose.yml
services:
  muf-terminal:
    build: .
    container_name: muf-terminal
    env_file:
      - .env
    environment:
      - LOCAL_WORKSPACE_FOLDER=${LOCAL_WORKSPACE_FOLDER:-..}
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-..}/muf:/app/muf
      - ${LOCAL_WORKSPACE_FOLDER:-.}/terminal:/app/terminal
    networks:
      - muf-network
    restart: always
    # 対話モードを有効にするための設定
    stdin_open: true
    tty: true
    command: python terminal/main.py

networks:
  muf-network:
    name: muf-network
