# muf/check-unit/docker-compose.yml
services:
  muf-check-unit:
    build:
      context: ..
      dockerfile: check-unit/Dockerfile
    container_name: muf-check-unit
    # .env ファイルから環境変数を読み込む設定を追加
    env_file:
      - .env
    environment:
      - LOCAL_WORKSPACE_FOLDER=${LOCAL_WORKSPACE_FOLDER:-..}
      - REDIS_HOST=muf-redis
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-..}/muf:/app/muf
      - ${LOCAL_WORKSPACE_FOLDER:-.}/check-unit:/app/check-unit
    networks:
      - muf-network

networks:
  muf-network:
    name: muf-network
